services:
  database-oracle:
    build:
      context: oracle
      dockerfile: Dockerfile-db-oracle
      tags:
        - localhost:32000/conf-oracle:latest
    image: localhost:32000/conf-oracle:latest
    ports:
      - PORT_DB:1521
    volumes:
      - ./init-script:/opt/oracle/scripts/setup
    deploy:
      resources:
        limits:
          memory: 4g
    healthcheck:
      test: [ "CMD-SHELL", "ls /opt/oracle/oradata/ORCLCDB/supportly.dbf" ]
      interval: 10s
      timeout: 5s
      retries: 360
      start_period: 20m



  backend-oracle:
    build:
      context: backend
      dockerfile: Dockerfile
      tags:
        - localhost:32000/conf-backend-oracle:latest
    image: localhost:32000/conf-backend-oracle:latest
    env_file:
      - ./backend/backend.env
    depends_on:
      database-oracle:
        condition: service_healthy
    ports:
      - PORT_BACKEND:8080


  frontend-oracle:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      tags:
        - localhost:32000/conf-frontend-oracle:latest
    image: localhost:32000/conf-frontend-oracle:latest
    depends_on:
      - backend-oracle
    ports:
      - PORT_FRONTEND:80

volumes:
  oracle-data: